# Generated by Django 5.2.1 on 2025-05-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("white", models.CharField(blank=True, max_length=255, null=True)),
                ("black", models.CharField(blank=True, max_length=255, null=True)),
                ("result", models.CharField(blank=True, max_length=10, null=True)),
                ("opening", models.CharField(blank=True, max_length=255, null=True)),
                ("eco", models.CharField(blank=True, max_length=10, null=True)),
                ("whiteelo", models.IntegerField(blank=True, null=True)),
                ("blackelo", models.IntegerField(blank=True, null=True)),
                ("event", models.CharField(blank=True, max_length=255, null=True)),
                ("site", models.CharField(blank=True, max_length=255, null=True)),
                ("tournament", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("enddate", models.DateField(blank=True, null=True)),
                ("endtime", models.TimeField(blank=True, null=True)),
                (
                    "timecontrol",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("link", models.URLField(blank=True, max_length=500, null=True)),
                ("pgn", models.TextField()),
                (
                    "pgn_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("source", models.CharField(db_index=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-endtime"],
                "indexes": [
                    models.Index(
                        fields=["date", "endtime"], name="repo_game_date_4609c9_idx"
                    ),
                    models.Index(fields=["white"], name="repo_game_white_2f866e_idx"),
                    models.Index(fields=["black"], name="repo_game_black_bc64e8_idx"),
                ],
            },
        ),
    ]
