# Generated by Django 5.2.1 on 2025-05-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={
                "ordering": ["-date", "-endtime"],
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
            },
        ),
        migrations.RenameIndex(
            model_name="game",
            new_name="games_date_a10f30_idx",
            old_name="repo_game_date_4609c9_idx",
        ),
        migrations.RenameIndex(
            model_name="game",
            new_name="games_white_2e28f8_idx",
            old_name="repo_game_white_2f866e_idx",
        ),
        migrations.RenameIndex(
            model_name="game",
            new_name="games_black_754b7d_idx",
            old_name="repo_game_black_bc64e8_idx",
        ),
        migrations.AlterModelTable(
            name="game",
            table="games",
        ),
    ]
