# Generated by Django 5.2.1 on 2025-05-09 03:36

import repo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0002_alter_game_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="date",
            field=repo.models.ChessDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="enddate",
            field=repo.models.ChessDateField(blank=True, null=True),
        ),
    ]
