# Generated by Django 5.2.1 on 2025-05-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0003_alter_game_date_alter_game_enddate"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="round",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="variant",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["tournament"], name="games_tournam_48fe0b_idx"),
        ),
    ]
