# Generated by Django 5.2.1 on 2025-05-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0004_game_round_game_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="format",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="source",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["source"], name="games_source_2baaef_idx"),
        ),
    ]
