# Generated by Django 5.2.1 on 2025-05-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0005_game_format_alter_game_source_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["date"], name="games_date_02ed81_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["date", "tournament", "source", "endtime"],
                name="games_date_c6f0d4_idx",
            ),
        ),
    ]
