# Generated by Django 5.2.1 on 2025-05-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0006_game_games_date_02ed81_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="game",
            name="games_source_2baaef_idx",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="games_date_c6f0d4_idx",
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["tournament", "endtime"], name="games_tournam_6f14e7_idx"
            ),
        ),
    ]
