# Generated by Django 5.2.1 on 2025-05-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0008_player_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="blackelo",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="whiteelo",
            field=models.CharField(blank=True, null=True),
        ),
    ]
