# Generated by Django 5.2.1 on 2025-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0009_alter_game_blackelo_alter_game_whiteelo"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="game",
            name="games_date_a10f30_idx",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="games_white_i_f97198_idx",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="games_black_i_fd5074_idx",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="games_tournam_48fe0b_idx",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="games_tournam_6f14e7_idx",
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["endtime"], name="games_endtime_c7faad_idx"),
        ),
    ]
